name: creatorcompanion

keys: false

env_file:
  - .env

proxy:
  app:
    - api.creatorcompanion.local.host:8000

services:
  redis:
    type: redis:7
    portforward: 6379
  app:
    type: python:3.10
    scanner: false
    moreHttpPorts:
      - "8000"
    overrides:
      ports:
        - 8000:8000
    build:
      - pip install --upgrade pip
      - pip install -r ./back_end/requirements.txt

tooling:
  pip:
    service: app
    cmd: pip
  dev:
    service: app
    cmd: uvicorn back_end.api:app --host 0.0.0.0 --port 8000 --reload
  celery:
    service: app
    cmd: celery -A back_end.tasks.watcher worker --loglevel=info
  watcher:
    service: app
    cmd: python -m back_end.tasks.watcher
  adk:
    service: app
    cmd: adk
